apiVersion: v1
kind: Config
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURKekNDQWcrZ0F3SUJBZ0lDQm5Vd0RRWUpLb1pJaHZjTkFRRUxCUUF3TXpFVk1CTUdBMVVFQ2hNTVJHbG4KYVhSaGJFOWpaV0Z1TVJvd0dBWURWUVFERXhGck9ITmhZWE1nUTJ4MWMzUmxjaUJEUVRBZUZ3MHlNekF4TWpreQpNVEF4TVRWYUZ3MDBNekF4TWpreU1UQXhNVFZhTURNeEZUQVRCZ05WQkFvVERFUnBaMmwwWVd4UFkyVmhiakVhCk1CZ0dBMVVFQXhNUmF6aHpZV0Z6SUVOc2RYTjBaWElnUTBFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUIKRHdBd2dnRUtBb0lCQVFEUVgxbEd4ZFRLckh1S3k1WC8reXNSclBoUmk5T29mZ3N6M2t5cjVRajk2T01WeW01cwpFdGsvd1pBYklxcmVVd3VwQTlmTjA5NUY4TERkWjZKZUJXUGNHa1dhYytDT1BjRGp6bG9jMGhQTEJkb2UwYUFMCk5nMDFIT3dscFhZUlJENzljOEd4MEZqYlBibXowUmdWRGhqcitBS0doVmlHRzZqOWprUTJHcjBFeitZd1MrNEQKZ3BJeHViaWwvV0FzdzdWRS9tcDNkaC9FejNOaytsRXBxV3F6RkczRkRsL3h6NWdkK2cwNFc2b1lYbnpQQTJIQgpTMW1zb01SVkZKU0dkRGFJOFhlT3oxOTdqQUtjWElqSlA0MWFYTUtSdU5rUnJoZGx6MkVSNnpXWWRVSnMxWkMzClEzaTNkNFJGY2t4TDJBUWxUaktrb3JlY0xCNm9NRlRDNEtoZkFnTUJBQUdqUlRCRE1BNEdBMVVkRHdFQi93UUUKQXdJQmhqQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUFNQjBHQTFVZERnUVdCQlNCV2UvTHBQdXRnZkFBSjdOcwpteDZNYVdUZStqQU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFvM0U3ZkRjNGdUUGxnV3pIcyt0N2pQcWZ6L2dYCmZ0cmxMVGFzcW5DcjZDNHVZeFhWL2V0WUFEV3Z6dkc1ZStMUVdjQ1lQeGpROUdRR0c0ZXpmWjN6V3RORnk4bkoKeUtkbzg5bW50aXlQQnNML1JDRlYxWmhVS3l1NUxRc2krUW41b1RGdXk2Rk8rN0lpYjZjdkJEL2tveXU5OUNRQgpKZkJWTXEzbUdWQndGZlJnLzFzNUoxb0x3SHdxSjgzaTNVQXlCeUFjZmJjZjd1WTY1QXlkV0JQZmNvK1hVcGhICndza0VSUzNjbTR1NHBhaTZGdXFmN3hxQmVncS9qNU5lUVowbVFYbVVPdE4yNDRFd05wYWNjZzhURmZGdy9iV28KN0hRYTcyYmpWM0xpNkNURTRoK1lPbWVIZzNBWEdCeWxKRC95RXI5MVE1MW5XcklVSjZvYm9pWDVVZz09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://c7bebaf3-8259-450c-9204-9e5305f4ea7f.k8s.ondigitalocean.com
  name: do-nyc1-k8s
contexts:
- context:
    cluster: do-nyc1-k8s
    user: do-nyc1-k8s-admin
  name: do-nyc1-k8s
current-context: do-nyc1-k8s
users:
- name: do-nyc1-k8s-admin
  user:
    token: dop_v1_86afa1b08dfcf8ad0f16322c47e5925dbec2a1592f63d19221dac2e671dc5462
